global:
  resolve_timeout: 5m
route:
  group_by: ['cluster']
  receiver: 'slack_general'
  routes:
  - match:
      severity: slack
    receiver: slack_general
  - match:
    receiver: slack_general
receivers:
- name: slack_general
  slack_configs:
  - api_url: $WEBHOOK_URL
    channel: '#demo'

