apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-deployment
  namespace: exercice3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: 549637939820.dkr.ecr.eu-west-1.amazonaws.com/webservice-test:0.0.2
        env:
        - name: PREFIX_PATH
          value: /
        ports:
        - containerPort: 8080
          name: rest-api-ws
        resources:
          limits:
            memory: "40Mi"
            cpu: "200m"
          requests:
            memory: "40Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ws-service
  namespace: exercice3
  labels:
    app: webservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: rest-api-ws
  selector:
    app: webservice
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ws-service
  namespace: exercice3
  labels:
    app: webservice
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: webservice
  endpoints:
  - port: rest-api-ws
    interval: 10s
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: exercice3
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: ws-service
          servicePort: 8080
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: sample-metrics-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ws-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metricName: webservice
      targetAverageValue: 5