apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ui-ing
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /prometheus
        backend:
          serviceName: prometheus-operated
          servicePort: 9090