apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ui-ing
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /_plugin/kibana
        backend:
          serviceName: elasticsearch-logging
          servicePort: 443