apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ui-ing
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /_plugin/kibana
        backend:
          serviceName: elasticsearch-logging
          servicePort: 443