apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager-ui-ing
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /alertmanager
        backend:
          serviceName: alertmanager-main
          servicePort: 9093